"""Shared plumbing for the editor writers."""

from __future__ import annotations

import re

from .._text import single_line
from ..color import Color
from ..cterm import cterm_index
from ..palette import Palette
from .groups import Group
from .roles import Roles

__all__ = ["slug", "header_lines", "resolve_group", "ResolvedGroup"]

# nvim_set_hl and vim's :highlight take the same attribute names.
ATTRIBUTES = ("bold", "italic", "underline", "undercurl", "strikethrough", "reverse")


def slug(name: str | None) -> str:
    """A colorscheme name vim will accept as `g:colors_name`."""
    candidate = re.sub(r"[^a-zA-Z0-9_-]+", "-", (name or "cscx").strip()).strip("-")
    return (candidate or "cscx").lower()


def header_lines(palette: Palette, roles: Roles, comment: str) -> list[str]:
    """The provenance banner, including where every role came from."""
    origin = f" from {palette.source_format}" if palette.source_format else ""
    lines = [
        f"{comment} {single_line(palette.name) or 'cscx'}",
        f"{comment} generated by cscx{origin}",
        comment,
        f"{comment} base16 role mapping."
        + ("" if roles.terminal_exact else " UI shades interpolated in OKLab;"),
    ]
    if not roles.terminal_exact:
        lines.append(f"{comment} comments held at a 4.5:1 contrast ratio.")
    else:
        lines.append(f"{comment} Palette colors only (--terminal-exact).")

    lines.append(comment)
    for role in sorted(roles.slots):
        color = roles.slots[role]
        source = roles.provenance.get(role, "")
        lines.append(f"{comment}   {role:<12} {color.hex}  {source}")

    for warning in roles.warnings:
        lines.append(comment)
        lines.append(f"{comment} NOTE: {single_line(warning, limit=400)}")
    return lines


class ResolvedGroup:
    """A `Group` with its role names turned into concrete colors."""

    __slots__ = ("name", "fg", "bg", "sp", "attrs", "link", "palette")

    def __init__(self, group: Group, roles: Roles, palette: Palette) -> None:
        self.name = group.name
        self.link = group.link
        self.fg: Color | None = roles.resolve(group.fg)
        self.bg: Color | None = roles.resolve(group.bg)
        self.sp: Color | None = roles.resolve(group.sp)
        self.attrs = group.attrs
        self.palette = palette

    def cterm(self, color: Color | None) -> int | None:
        return None if color is None else cterm_index(color, self.palette)

    @property
    def is_empty(self) -> bool:
        """True when nothing survived resolution, so the group is skipped."""
        return not (self.fg or self.bg or self.sp or self.attrs or self.link)


def resolve_group(group: Group, roles: Roles, palette: Palette) -> ResolvedGroup:
    return ResolvedGroup(group, roles, palette)
