"""Emacs theme output (`NAME-theme.el`).

Built-in faces only. Package faces -- company, flycheck, magit and the rest --
would be guesswork about what the user has installed, and a face spec for an
unloaded package is inert rather than useful.

The theme also sets `ansi-color-names-vector`, so shell and compilation
buffers use the same sixteen colors as the terminal the theme came from.
"""

from __future__ import annotations

from .._text import elisp_string
from ..palette import Palette
from ._common import header_lines, resolve_group, slug
from .groups import EMACS
from .roles import CONTRAST_TARGET, derive

NAME = "emacs"
EXTENSION = ".el"
FILENAME = "{name}-theme.el"
BINARY = False
INSTALL_PATH = "~/.emacs.d/themes/{name}-theme.el"

# Emacs spells face attributes as keyword properties rather than flags.
_ATTRIBUTES = {
    "bold": ":weight bold",
    "italic": ":slant italic",
    "underline": ":underline t",
    "strikethrough": ":strike-through t",
    "reverse": ":inverse-video t",
}


def emit(
    palette: Palette,
    *,
    terminal_exact: bool = False,
    contrast_target: float = CONTRAST_TARGET,
) -> str:
    roles = derive(palette, terminal_exact=terminal_exact, contrast_target=contrast_target)
    name = slug(palette.name)

    lines = [
        f";;; {name}-theme.el --- {name} -*- lexical-binding: t; -*-",
        ";;; Commentary:",
    ]
    lines += header_lines(palette, roles, ";;")
    lines += [
        ";;",
        f";; install as {INSTALL_PATH.format(name=name)}, then",
        f";; (load-theme '{name} t)",
        ";;; Code:",
        "",
        f"(deftheme {name}",
        f"  {elisp_string(f'{palette.name or name}, generated by cscx')})",
        "",
        "(custom-theme-set-faces",
        f" '{name}",
    ]

    for group in EMACS:
        resolved = resolve_group(group, roles, palette)
        if not resolved.is_empty:
            lines.append(f" '({resolved.name} ((t ({_face(resolved)}))))")
    lines.append(" )")

    if all(color is not None for color in palette.ansi):
        colors = " ".join(f'"{c.hex}"' for c in palette.ansi)
        lines += [
            "",
            ";; Shell and compilation buffers, matching the source terminal.",
            "(custom-theme-set-variables",
            f" '{name}",
            f" '(ansi-color-names-vector [{colors}]))",
        ]

    lines += [
        "",
        f"(provide-theme '{name})",
        "",
        f";;; {name}-theme.el ends here",
    ]
    return "\n".join(lines) + "\n"


def _face(resolved) -> str:
    """The property list for one face spec."""
    parts = []
    if resolved.fg:
        parts.append(f':foreground "{resolved.fg.hex}"')
    if resolved.bg:
        parts.append(f':background "{resolved.bg.hex}"')

    for attribute in resolved.attrs:
        if attribute == "undercurl":
            colour = f' :color "{resolved.sp.hex}"' if resolved.sp else ""
            parts.append(f":underline (:style wave{colour})")
        elif attribute in _ATTRIBUTES:
            parts.append(_ATTRIBUTES[attribute])

    return " ".join(parts)
