"""Helpers shared by the emitters."""

from __future__ import annotations

from .._text import single_line
from ..fill import Derivations

__all__ = ["header", "note", "note_line", "GENERATED_BY"]

GENERATED_BY = "generated by cscx"


def header(palette, comment: str = "#") -> list[str]:
    """The provenance banner every text format opens with."""
    lines = []
    if name := single_line(palette.name):
        lines.append(f"{comment} {name}")
    origin = f" from {palette.source_format}" if palette.source_format else ""
    lines.append(f"{comment} {GENERATED_BY}{origin}")
    return lines


def note(derived: Derivations | None, field: str, comment: str = "#") -> str:
    """A trailing `# derived: foreground` marker, or nothing.

    Emitters call this so a filled value is never mistaken for one the source
    actually specified.
    """
    if not derived or field not in derived:
        return ""
    return f"  {comment} derived: {derived[field]}"


def note_line(derived: Derivations | None, field: str, comment: str = "#") -> list[str]:
    """The same marker as `note`, but as its own line.

    ghostty and X resources have no inline comment syntax -- `xrdb` reads a
    trailing `! black` as part of the value -- so annotations for those
    formats go above the line they describe.
    """
    if not derived or field not in derived:
        return []
    return [f"{comment} derived: {derived[field]}"]
